version: '3'
services:
  weather-app:
    container_name: weather-app
    build:
      context: ./app
    expose:
      - "5000"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8000:80"  
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - weather-app