FROM jenkins/inbound-agent:latest

USER root

# Install Git, Docker CLI, and Python
RUN apt-get update && apt-get install -y \
    git \
    python3 \
    python3-pip \
    docker.io \
 && rm -rf /var/lib/apt/lists/*

# Optional: set default Python
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1

# Back to jenkins user
USER jenkins

